### ISSUE TITLE
Min/Max values in Example YAML

### ISSUE THREAD

**Issue by MageoMage** [DeamonHunter/ArchipelagoMuseDash#21]
Would be great to have the ranges of valid values in the example YAML again because i was just confused for a second why the additional item percentage of 10 was invalid, since I didn't notice that there was a change to that, or in general can be helpful for when you create a YAML yourself and don't want to look at the entire code history or the code.

**Comment by DeamonHunter** [comment]
Oops. That was an undocumented change.

The v0.8.0 release has been updated with a new Example.yaml which has the ranges and defaults in it. And the changelog was added to reflect the minimum additional item percentage.
